### ISSUE TITLE
Velocity plugin support

### ISSUE THREAD

**Issue by invisicat** [Cubxity/docker-minecraft-proxy#1]
Will you ever provide auto-download support for plugins as with what @itzg did with his image with spiget?

**Comment by itzg** [comment]
Interesting point, I could also add the Spiget support over in the bungeecord image 

https://github.com/itzg/docker-bungeecord

**Comment by Cubxity** [comment]
I will most likely not add support for this in my image. The goal with this image is to build an immutable server image.
